In [1]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
file_path = '/media/data/projects/crophisto/data.csv'
crop_codes = '/media/data/projects/crophisto/crop_codes.csv'

# load crop info
df_crops = pd.read_csv(crop_codes, sep=";")

# create vocab map
crop_map = {row["code"]:row["description"] for index, row in df_crops[["code", "description"]].iterrows()}


In [3]:
df_crops

code                  description  is_crop
0      1                        TRIGO        1
1      3                URBANO-VIALES        0
2      4                         MAIZ        1
3      5                       CEBADA        1
4      8               OTROS CEREALES        1
5      9                     ROQUEDOS        0
6     20                SUELO DESNUDO        1
7     33                      GIRASOL        1
8     35                        COLZA        1
9     39      OTRAS LEGUMINOSAS GRANO        1
10    40                    GUISANTES        1
11    60                      ALFALFA        1
12    61                   FORRAJERAS        1
13    80  OTROS CULTIVOS INDUSTRIALES        1
14    82                    REMOLACHA        1
15    94                      PATATAS        1
16   100                       VIÑEDO        1
17   101                       OLIVAR        1
18   110                    HORTICOLA        1
19   177                   AROMATICAS        1
20   181                     FRUTALES        1
21   183             FRUTALES CASCARA        1
22   200                     PASTIZAL        0
23   201                     MATORRAL        0
24   202                    CONIFERAS        0
25   203       FRONDOSAS CADUCIFOLIAS        0
26   204     FRONDOSAS SIEMPRE VERDES        0
27   255                  LAMINA AGUA        0
28    52                       ERROR1        1

In [4]:
# load dataframe
df = pd.read_csv(file_path)
cols = ['C_TIPO_EXP','Holding__1','C_ZONA_AGR',
        'crop2011', 'crop2012', 'crop2013', 'crop2014', 'crop2016', 'crop2015', 'crop2017', 'crop2018', 'crop2019']


# data = np.zeros(shape=[df.shape[0], 9], dtype=np.int8)

# for index, row in df[cols].iterrows():
#     lst = row.tolist()
#     lst_conv = [vocab[x] for x in lst]
#     data[index, :] = lst_conv

    
# print(data.shape)



In [5]:
mask = df["C_TIPO_EXP"] =="S"
# df[]["C_TIPO_EXP"] = 0
# df[df["C_TIPO_EXP"] =="R"]["C_TIPO_EXP"] = 1
df.loc[mask, ["C_TIPO_EXP"]] = 0
df.loc[~mask, ["C_TIPO_EXP"]] = 1
df.head()

Join_Count  TARGET_FID  C_PRODUCTO  C_TIPO_EXP   SUPERFICIE  C_ZONA_AGR  \
0           1     1557935          20           0  3659.745253           5   
1           1     1557936          20           0  3145.595066           5   
2           1     1557937          20           0  1148.254304           5   
3           1     1557938          20           0  3155.065480           5   
4           1     1557939          20           0   782.876447           5   

   COD_CULTIV     F_CARGA  C_CICLO C_SCENARIO  ...  crop2012  crop2013  \
0          20  2020-01-20        0        BSO  ...         1         1   
1          20  2020-01-20        0        BSO  ...        20         1   
2          20  2020-01-20        0        BSO  ...         1         1   
3          20  2020-01-20        0        BSO  ...       201         1   
4          20  2020-01-20        0        BSO  ...        61       201   

   crop2014  crop2016  crop2015  crop2017  crop2018  crop2019    FOI_ID  \
0       201         8         1        20         8        20  11227689   
1        61         1         8        20         1        61  11227690   
2        61       200        20       200       200       200  11227691   
3       201         1         1         1         8        20  11227692   
4         8         1         8         5         1        20  11227693   

   Holding__1  
0    42200496  
1    42200496  
2    42200496  
3    42200496  
4    42200496  

[5 rows x 25 columns]

In [6]:
df[df["crop2012"] == 3]

Join_Count  TARGET_FID  C_PRODUCTO  C_TIPO_EXP   SUPERFICIE  \
5204              1     1563139           5           0  1118.419992   
5296              1     1563231           1           0  1691.426845   
5340              1     1563275           1           0   948.765138   
5766              1     1563701          60           1  1312.278660   
6071              1     1564006           1           0   713.199045   
...             ...         ...         ...         ...          ...   
2132794           1     1550811          20           0  2390.109625   
2132841           1     1550858           5           0   720.471463   
2134198           1     1552215          20           1   554.618324   
2135931           1     1553948           5           1  2574.029117   
2136016           1     1554033           1           0  1630.624893   

         C_ZONA_AGR  COD_CULTIV     F_CARGA  C_CICLO C_SCENARIO  ...  \
5204              3          32  2020-01-20        1        CHI  ...   
5296              4          31  2020-01-20        1        CHI  ...   
5340              4          31  2020-01-20        1        CHI  ...   
5766              3           2  2020-01-20        0        CHP  ...   
6071              3          31  2020-01-20        1        CHI  ...   
...             ...         ...         ...      ...        ...  ...   
2132794           3          20  2020-01-20        0        BSO  ...   
2132841           3          32  2020-01-20        1        CHI  ...   
2134198           3          20  2020-01-20        0        BSO  ...   
2135931           4          32  2020-01-20        1        CHI  ...   
2136016           4          31  2020-01-20        1        CHI  ...   

         crop2012  crop2013  crop2014  crop2016  crop2015  crop2017  crop2018  \
5204            3         3         3         3         3         5         5   
5296            3         3         3         3         1         1         5   
5340            3         3         3         3         3         3         3   
5766            3         5        61         3        94         3        20   
6071            3         5         5         3         5         1        20   
...           ...       ...       ...       ...       ...       ...       ...   
2132794         3         3         5       110        20        20         5   
2132841         3         3         3         3         3       200         5   
2134198         3         3       201         3         3         3         3   
2135931         3         5        61         1       202        33         1   
2136016         3         3         1         1         3         1         1   

         crop2019    FOI_ID  Holding__1  
5204            1  11233995    42200610  
5296            1  11231296    42200563  
5340            3  11232258    42200571  
5766            1  11234314    42200612  
6071            5  11230723    42200551  
...           ...       ...         ...  
2132794        20  11220039    42200340  
2132841         5  11220874    42200364  
2134198         3  11208662    42101826  
2135931         5  11208848    42101828  
2136016         1  11210410    42101858  

[3417 rows x 25 columns]

In [19]:
print(">>>>Valores en y")
y = df['crop2019']

crop_codes = df_crops["code"]

for code in crop_codes:
    print("code: {} - {}: {}".format(code, crop_map[code], y[y==code].shape[0]))

print(">>>>Valores en X")
# crop_cols = [x for x in cols if x.startswith("crop")]
X = df[cols[:-1]]
for code in crop_codes:
    print("code: {} - {}: {}".format(code, crop_map[code],  X[(X[:]==code).any(1)].shape[0]))    

X.shape


>>>>Valores en y
code: 1 - 0: 462888
code: 3 - 1: 38443
code: 4 - 2: 54199
code: 5 - 3: 337891
code: 8 - 4: 89706
code: 9 - 5: 1196
code: 20 - 6: 328147
code: 33 - 7: 128978
code: 35 - 8: 4255
code: 39 - 9: 9931
code: 40 - 10: 13151
code: 60 - 11: 47632
code: 61 - 12: 55395
code: 80 - 13: 817
code: 82 - 14: 6878
code: 100 - 15: 25631
code: 101 - 16: 6923
code: 110 - 17: 3176
code: 177 - 18: 7201
code: 181 - 19: 8657
code: 183 - 20: 3806
code: 200 - 21: 261095
code: 201 - 22: 96606
code: 202 - 23: 11556
code: 203 - 24: 60894
code: 204 - 25: 74487
code: 255 - 26: 378
>>>>Valores en X
code: 1 - 0: 1397012
code: 3 - 1: 597091
code: 4 - 2: 625827
code: 5 - 3: 1289441
code: 8 - 4: 381635
code: 9 - 5: 17098
code: 20 - 6: 819289
code: 33 - 7: 658450
code: 35 - 8: 47721
code: 39 - 9: 341834
code: 40 - 10: 90877
code: 60 - 11: 156941
code: 61 - 12: 398322
code: 80 - 13: 15532
code: 82 - 14: 51160
code: 100 - 15: 50641
code: 101 - 16: 15044
code: 110 - 17: 71629
code: 177 - 18: 31512
code: 181 - 

(2139917, 11)

In [20]:
# remove all rows with code "52" -> and 94 -> 15


crops_to_remove = [52, 94]

# remove rows  with category 28
filtered = df
print(filtered.shape)
for code in crops_to_remove:
    filtered =filtered[~ (filtered[:]==code).any(1)]
    print(filtered.shape)


df_crops = df_crops[~(df_crops["code"].isin(crops_to_remove ))]
df_crops.to_pickle("/media/data/projects/crophisto/crop_codes.pckl")
df_crops


(2139917, 25)
(2036270, 25)
(1984471, 25)


code                  description  is_crop  idx
0      1                        TRIGO        1    0
1      3                URBANO-VIALES        0    1
2      4                         MAIZ        1    2
3      5                       CEBADA        1    3
4      8               OTROS CEREALES        1    4
5      9                     ROQUEDOS        0    5
6     20                SUELO DESNUDO        1    6
7     33                      GIRASOL        1    7
8     35                        COLZA        1    8
9     39      OTRAS LEGUMINOSAS GRANO        1    9
10    40                    GUISANTES        1   10
11    60                      ALFALFA        1   11
12    61                   FORRAJERAS        1   12
13    80  OTROS CULTIVOS INDUSTRIALES        1   13
14    82                    REMOLACHA        1   14
16   100                       VIÑEDO        1   16
17   101                       OLIVAR        1   17
18   110                    HORTICOLA        1   18
19   177                   AROMATICAS        1   19
20   181                     FRUTALES        1   20
21   183             FRUTALES CASCARA        1   21
22   200                     PASTIZAL        0   22
23   201                     MATORRAL        0   23
24   202                    CONIFERAS        0   24
25   203       FRONDOSAS CADUCIFOLIAS        0   25
26   204     FRONDOSAS SIEMPRE VERDES        0   26
27   255                  LAMINA AGUA        0   27

In [21]:
df_crops["idx"] = df_crops.index
df_crops

code                  description  is_crop  idx
0      1                        TRIGO        1    0
1      3                URBANO-VIALES        0    1
2      4                         MAIZ        1    2
3      5                       CEBADA        1    3
4      8               OTROS CEREALES        1    4
5      9                     ROQUEDOS        0    5
6     20                SUELO DESNUDO        1    6
7     33                      GIRASOL        1    7
8     35                        COLZA        1    8
9     39      OTRAS LEGUMINOSAS GRANO        1    9
10    40                    GUISANTES        1   10
11    60                      ALFALFA        1   11
12    61                   FORRAJERAS        1   12
13    80  OTROS CULTIVOS INDUSTRIALES        1   13
14    82                    REMOLACHA        1   14
16   100                       VIÑEDO        1   16
17   101                       OLIVAR        1   17
18   110                    HORTICOLA        1   18
19   177                   AROMATICAS        1   19
20   181                     FRUTALES        1   20
21   183             FRUTALES CASCARA        1   21
22   200                     PASTIZAL        0   22
23   201                     MATORRAL        0   23
24   202                    CONIFERAS        0   24
25   203       FRONDOSAS CADUCIFOLIAS        0   25
26   204     FRONDOSAS SIEMPRE VERDES        0   26
27   255                  LAMINA AGUA        0   27

In [22]:
#convert data to codes
# df_outer = pd.merge(df1, df2, on='id', how='outer')

In [40]:
data = filtered[cols].values.astype(np.int16)


crop_list = df_crops["code"].to_numpy()
crop_map = {val: idx for idx, val in enumerate(crop_list)}
print(crop_map)
print("Num cultivos: {}".format(len(crop_map)))


# conv_data = np.zeros(shape=data.shape, dtype=np.int8)
# index = 0
# for row in data:
#     lst_conv = [crop_map[x] for x in row]
#     conv_data[index, :] = lst_conv
#     index+=1



data_file = "/media/data/projects/crophisto/data.npy"
np.save(data_file, data)

{1: 0, 3: 1, 4: 2, 5: 3, 8: 4, 9: 5, 20: 6, 33: 7, 35: 8, 39: 9, 40: 10, 60: 11, 61: 12, 80: 13, 82: 14, 100: 15, 101: 16, 110: 17, 177: 18, 181: 19, 183: 20, 200: 21, 201: 22, 202: 23, 203: 24, 204: 25, 255: 26}
Num cultivos: 27


In [38]:
data.max()


32767

In [60]:
data_file = "/media/data/projects/crophisto/data.npy"
data = np.load(data_file)
print(data.shape)
y = data[:, 11]
X1 = data[:,:3]
X2 = data[:, 3:11]

print("y: {}, X1: {}, X2: {}".format(y.shape, X1.shape, X2.shape))

print(data[0,:])
print(y[0])
print(X1[0,:])
print(X2[0,:])




(1984471, 12)
y: (1984471,), X1: (1984471, 3), X2: (1984471, 8)
[    0 -4688     5   201     1     1   201     8     1    20     8    20]
20
[    0 -4688     5]
[201   1   1 201   8   1  20   8]


In [ ]:

print(np.unique(X))

print(np.unique(y))
